name: Check PR

on: pull_request
permissions: read-all

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Run pre-commit
        uses: govuk-one-login/github-actions/code-quality/run-pre-commit@cd7d35dde348251237efbbaee5345e95adef0321
        with:
          all-files: true

  unit-tests:
    name: Run tests
    uses: ./.github/workflows/run-unit-tests.yml
