name: Run Browser Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  browser:
    runs-on: ubuntu-latest
    permissions: {}

    steps:
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Start Docker
        run: docker compose up web mocks --detach
        working-directory: tests/docker

      - name: Run Cucumber tests
        run: docker compose up cucumber --exit-code-from cucumber
        working-directory: tests/docker

      - name: Stop Docker
        run: docker compose down
        working-directory: tests/docker
        if: ${{ always() }}
